@startuml
       title 基于GitHub的实验管理平台--发布实验用例的顺序图
       actor teacher
       teacher -> course: 选择指定课程
       activate course
       activate teacher
       course -> experiment: 填写实验名称，目的，过程等
       activate experiment
       experiment ->teacher:发布结果信息返回
       deactivate experiment
       deactivate teacher
       deactivate course

       @enduml